name: Deployments
on:
  workflow_dispatch:
  schedule:
    # every 10 mins
    - cron: "*/10 * * * *"

jobs:
  cleanup:
    name: Clean up integration environment deployments
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09 # v2.5.1
        with:
          egress-policy: audit

      - name: Checkout repo
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0

      - name: 🧼 Clean up Environment
        uses: ./.github/actions/delete-deployments
        with:
          environment: integration
          # Delete 300 deployments at a time
          num-of-pages: 3
          # We start with page 2 because usually the first 200 deployments are still active, so we cannot delete them
          starting-page: 2

      - name: Collect Metrics
        id: collect-gha-metrics
        uses: smartcontractkit/push-gha-metrics-action@d2c2b7bdc9012651230b2608a1bcb0c48538b6ec
        with:
          basic-auth: ${{ secrets.GRAFANA_CLOUD_BASIC_AUTH }}
          hostname: ${{ secrets.GRAFANA_CLOUD_HOST }}
          this-job-name: Clean up integration environment deployments
        continue-on-error: true
